### ISSUE TITLE
Add bullets

### ISSUE THREAD

**Issue by rnestler** [coredump-ch/rpsrtsrs#55]
Units should be able to fire bullets.

### Questions

 * Should they have a range?
 * Should they have a speed or hit just instant (laser-like)?
 * Should units autofire?
 * Should units calculate how to fire on moving targets?

### Tasks

- [x] Add bullets to `GameState`
- [ ] Add collision detection for bullets
- [x] Implement fire command
- [ ] Handle killed Units
